-- CreateEnum
CREATE TYPE "LoggedStatus" AS ENUM ('LOGGED', 'NOT_LOGGED');

-- AlterTable
ALTER TABLE "Trip" ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "logged" "LoggedStatus" NOT NULL DEFAULT 'NOT_LOGGED',
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
